INSERT INTO role (name) VALUES ('DEV_ADMIN') ON DUPLICATE KEY UPDATE name=name;
INSERT INTO role (name) VALUES ('UNIFI') ON DUPLICATE KEY UPDATE name=name;
INSERT INTO role (name) VALUES ('AGENCY_ADMIN') ON DUPLICATE KEY UPDATE name=name;
INSERT INTO role (name) VALUES ('AGENT') ON DUPLICATE KEY UPDATE name=name;
INSERT INTO role (name) VALUES ('UCONNECT') ON DUPLICATE KEY UPDATE name=name;
INSERT INTO role (name) VALUES ('USER') ON DUPLICATE KEY UPDATE name=name;